name: CI for images 

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - 
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SA_KEY}}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true
     - name: build image 
       run: |-
        docker build . --file ./Dockerfile --tag us.gcr.io/$PROJECT_ID/newapp:latest
     - name: helper
       run: |
        gcloud auth configure-docker -q
     - name: image push
       run: |-
        docker push us.gcr.io/$PROJECT_ID/newapp:latest
